#!/usr/bin/env bash
# Install nginx to server
# GET request must be responded by the string 'Hello, World!'
apt update
apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
