#!/usr/bin/env bash
# Install nginx to server
# GET request to root must be responded by the string 'Hello, World!'
# GET request to /redirect_me/ must be redirected permanently

sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
text="\\\tlocation /redirect_me/ {\n\t\trewrite ^(.*)$ http://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"
sudo sed -i "19i $text" /etc/nginx/sites-available/default
sudo service nginx restart
