#!/usr/bin/env bash
# prints "Best School" & "Hi" with while and if conditions
TEXT="Best School"
COUNT=1

while [ $COUNT -le 10 ]; do
	echo "$TEXT"
	if [ $COUNT = 9 ];
	then
		echo "Hi"
	fi
	COUNT=$((COUNT + 1))
done
