#!/usr/bin/env bash
# conditionally prints 3 texts 10 times
TEXT1="bad luck"
TEXT2="good luck"
DEFAULT_TEXT="Best School"
COUNT=1

while [ $COUNT -le 10 ]; do
	if [ $COUNT = 4 ];
	then
		echo "$TEXT1"
	elif [ $COUNT = 8 ];
	then
		echo "$TEXT2"
	else
		echo "$DEFAULT_TEXT"
	fi
	COUNT=$((COUNT + 1))
done
