#!/usr/bin/env bash
# gives information about the file called 'school'

if [ -e ./school ];
then
	echo "school file exists"

	if test -f school;
	then
		if [ -s ./school ];
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		echo "school is a regular file"
	fi

	if test -d school;
	then
		if [ -s ./school ];
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
	fi
else
	echo "school file does not exist"
fi
