#!/usr/bin/env bash
# local host to 127.0.0.2 and facebook to 8.8.8.8
cp /etc/hosts ~/new_hosts

sed - 's/127.0.0.1/127.0.0.2 localhost/; s/8.8.8.8 facebook.com/' ~/new_hosts

cp -f ~/new_hosts /etc/hosts
